AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-dynamodb

  Sample SAM Template for lambda-dynamodb
  
Globals:
  Function:
    Timeout: 10

Resources:
  UserPaths:
    Type: AWS::Serverless::Application
    Properties:
      Location: gateway/user.yaml
      Parameters:
        UserTable: !Ref UserTable
  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: usersDB
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
