AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters: 
  UserTable: 
    Type: String
    Description: Table where the user details are stored

Globals:
  Function:
    Timeout: 10

Resources:
 # API Gateway
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: Lambda-Dynamo-Api
      StageName: dev
      EndpointConfiguration: REGIONAL
      Cors:
        AllowOrigin: "'*'"      
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
  FetchAllUsers:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: ../user/
      Handler: app.FetchAllUsers
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        FetchAllUsers:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /FetchAllUsers
            Method: GET
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UserTable
  CreateUsers:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: ../user/
      Handler: app.CreateUsers
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        CreateUsers:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /CreateUsers
            Method: POST
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UserTable
  DeleteUser:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: ../user/
      Handler: app.DeleteUser
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        DeleteUser:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /DeleteUser
            Method: DELETE
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UserTable
  UpdateUser:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: ../user/
      Handler: app.UpdateUser
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        UpdateUser:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /UpdateUser
            Method: PUT
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UserTable